# Generated by Django 4.0.4 on 2022-05-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='numbers',
        ),
        migrations.AddField(
            model_name='signup',
            name='number',
            field=models.CharField(default=7.3, max_length=50),
            preserve_default=False,
        ),
    ]
